services:

  hosteypic_ngnix:
    command: nginx -g "daemon off;"
    container_name: hosteypic_nginx
    image: nginx:1.27.2
    restart: always
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
      - ./client/dist/uploads/:/client/dist/uploads
#     - ./client/src/assets/:/client/src/assets       # Не трогать
    ports:
      - "80:80"
    networks:
      - hosteypic

  hosteypic_server:
    tty: true
    container_name: hosteypic_server
    image: hosteypic_server
    build:
      context: ./server/
    volumes:
      - ./server/:/src/app
      - ./client/dist/uploads:/src/app/uploads
    command: sh -c "sleep 15 && alembic upgrade head && uvicorn hosteypic_server.main:app --host 0.0.0.0 --reload"
    links:
      - hosteypic_postgres
    depends_on:
      - hosteypic_postgres
    environment:
      DB_HOST: hosteypic_postgres   # WARNING ONLY FOR DEVELOPMENT!
      DB_NAME: db_hosteypic
      DB_USER: admin
      DB_PASS: my_super_password
      DB_PORT: 5432
      FRONTEND_URL: "http://localhost/"
      MAIL_HOST: "localhost"
      MAIL_PORT: 25
      MAIL_USE_TLS: False
      MAIL_USE_SSL: False
      MAIL_DEFAULT_SENDER: "noreply@example.com"
      DEBUG: True
    restart: always
    networks:
      - hosteypic

  hosteypic_client:
    tty: true
    container_name: hosteypic_client
    image: hosteypic_client
    build:
      context: client/
    environment:
      VITE_BACKEND_URL: "http://localhost/api/"
      DEBUG: "True"
    restart: on-failure
    networks:
      - hosteypic

  hosteypic_postgres:
    image: postgres:17.0
    container_name: hosteypic_postgres
    environment:
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my_super_password
      POSTGRES_DB: db_hosteypic
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"
    volumes:
      - ./backup:/backup
      - pgdata:/var/lib/postgresql/data/pgdata/
    restart: always
    tty: true
    stdin_open: true
    #    healthcheck:
    #      test: ["CMD-SHELL", "pg_isready -U admin -d db_hosteypic"]
    #      interval: 10s
    #      timeout: 5s
    #      retries: 5
    #      start_period: 10s
    networks:
      - hosteypic

  hosteypic_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hosteypic_pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@hosteypic.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin/data
    networks:
      - hosteypic

volumes:
  pgdata:

networks:
  hosteypic:
    external: false
