FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    postfix \
    ca-certificates \
    && apt-get clean

RUN apt-get install -y opendkim opendkim-tools \
    && apt-get clean

RUN cp /etc/host.conf /var/spool/postfix/etc/ \
    && cp /etc/resolv.conf /var/spool/postfix/etc/ \
    && cp /etc/services /var/spool/postfix/etc/

#RUN mkdir -p /var/spool/postfix/opendkim \
#    && chown postfix:opendkim /var/spool/postfix/opendkim \
#    && chmod 750 /var/spool/postfix/opendkim

RUN adduser postfix opendkim

COPY ./certs/fullchain.pem /etc/ssl/certs
COPY ./certs/privkey.pem /etc/ssl/private
COPY ./postfix/main.cf /etc/postfix
COPY ./postfix/master.cf /etc/postfix
COPY ./opendkim/opendkim.conf /etc
COPY ./opendkim /etc/default
COPY ./opendkim/keytable /etc/postfix/dkim
COPY ./opendkim/signingtable /etc/postfix/dkim

EXPOSE 25 587

CMD ["postfix", "start-fg"]
