"""Add users allowlist

Revision ID: bc0159da37e8
Revises: 7e2f3d27db8f
Create Date: 2024-11-24 19:39:17.393624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0159da37e8'
down_revision: Union[str, None] = '7e2f3d27db8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_allowlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_allowlist_email'), 'email_allowlist', ['email'], unique=True)
    op.drop_index('idx_gin_post', table_name='posts', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_gin_post', 'posts', [sa.text("to_tsvector(lang, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(body, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_email_allowlist_email'), table_name='email_allowlist')
    op.drop_table('email_allowlist')
    # ### end Alembic commands ###
